### ISSUE TITLE
indicator doesn't move on color picker

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#13]
When I right click a color on the canvas, the pen color changes.  However, The indicator on the color picker does not change to the current color.

**Comment by DevanshCodes** [comment]
Can I work on this?

**Comment by dfirebaugh** [comment]
go for it

**Comment by dfirebaugh** [comment]
I made some changes you might be interested in.

The indicators are now inside of the Context_t objects (rather than being a global).

So you would probably want to call this function and pass in the `color_picker_ctx` and the index that it should focus to.  That may be the same as the current pen color.

https://github.com/dfirebaugh/spritely/blob/e2132ac5b49bce9483f18a2cc2d4f2a52a396ec7/src/context.h#L30

Let me know if you have any questions.
