### ISSUE TITLE
Add 'hacktoberfest' topic to repository

### ISSUE THREAD

**Issue by Costava** [dfirebaugh/spritely#20]
This repo has issues with the label `hacktoberfest` and is participating in Hacktoberfest.

As per https://github.com/digitalocean/hacktoberfest/pull/596
Repositories must now opt in to Hacktoberfest by adding the topic `hacktoberfest` to the repo.

This can be done by the repo owners on the right side of the [main repo page](https://github.com/dfirebaugh/spritely)

**Comment by dfirebaugh** [comment]
Thanks,
I added the topic to the repo.  

I will review the pending PRs in a few hours
