### ISSUE TITLE
add keybindings to the README

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#27]
It would be good to have the keyboard shortcuts/bindings in the readme

you can find the current keybindings in the [input.c](https://github.com/dfirebaugh/spritely/blob/master/src/input.c) file or run the app and press f1 for the help menu

**Comment by gokulkannan7** [comment]
@dfirebaugh can I work on this?

**Comment by dfirebaugh** [comment]
sure

**Comment by gokulkannan7** [comment]
@dfirebaugh I have created a PR, pls do check
