### ISSUE TITLE
help info needs to be larger

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#30]
We've added so much to the help menu (the thing that pops up when you press `F1`) that it's all smooshed.

Let's make it a bit bigger.

**Comment by bexrr** [comment]
I would love to work on this :)

**Comment by dfirebaugh** [comment]
It would be appreciated!

Let us know if you have any questions.

Thanks

**Comment by dfirebaugh** [comment]
@bexrr there are a few items in the help screen that are missing new lines `\n`.  Could you add those while you're in there?

https://github.com/dfirebaugh/spritely/blob/beb544f1d9894a717db6bbe02585a8db6ab14e52/src/input.c#L17
