### ISSUE TITLE
Add github action to depoy wasm build to gh-pages

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#36]
current gh-pages deployment can be seen here
demo: https://dfirebaugh.github.io/spritely/
code: https://github.com/dfirebaugh/spritely/tree/gh-pages

When we pull into master branch, automatically build and deploy the web folder.
Instructions for building the web folder are in this projects `README.md`

**Comment by xNetcat** [comment]
I would like to get assigned to this.

**Comment by dfirebaugh** [comment]
You got it.

Thanks, let me know if you have any questions.
