### ISSUE TITLE
Draw some icons for our toolbar

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#38]
Use the tool to draw some icons for our tools that will be on the toolbar.

We need

- pen tool
- fill tool
- undo
- redo
- save
- load
- drag

Make an assets folder and save the output png file.

You don't have a lot of pixels to work with.  So, make them count!

**Comment by 72y9op** [comment]
Hellow ! I'm graphist, i can help you, what is the size you want ?

**Comment by dfirebaugh** [comment]
the size is 8 pixels by 8 pixels

**Comment by 72y9op** [comment]
Okay i make that ! :smile:

**Comment by dfirebaugh** [comment]
Oh, also a icon to open the help info.  (i.e. what shows up when you press F1)

**Comment by 72y9op** [comment]
@dfirebaugh Okay all design are created, i have move it in `assets/icons/*.png`

- pen tool ![pen](https://raw.githubusercontent.com/72y9op/spritely/master/assets/icons/Pen.png)
- fill tool ![fill](https://raw.githubusercontent.com/72y9op/spritely/master/assets/icons/Fill.png)
- undo ![undo](https://raw.githubusercontent.com/72y9op/spritely/master/assets/icons/Undo.png)
- redo ![redo](https://raw.githubusercontent.com/72y9op/spritely/master/assets/icons/Redo.png)
- save ![save](https://raw.githubusercontent.com/72y9op/spritely/master/assets/icons/Save.png)
- load ![load](https://raw.githubusercontent.com/72y9op/spritely/master/assets/icons/Load.png)
- drag ![drag](https://raw.githubusercontent.com/72y9op/spritely/master/assets/icons/Drag.png)
- info ![info](https://raw.githubusercontent.com/72y9op/spritely/master/assets/icons/Info.png)

Say me if it's all you want :smile: and say me if i can do a PR

**Comment by dfirebaugh** [comment]
These are great!  Nice work
Yeah, do a PR.

haha
