### ISSUE TITLE
Make the font prettier

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#46]
All lowercase might look better.

We load the font in as a sprite sheet.  Each character is 8 pixels by 8 pixels.

You can edit this in any tool that you want, but the characters must fit in their 8x8 quads.

![font_sprite_sheet](https://raw.githubusercontent.com/dfirebaugh/spritely/master/assets/font/alpha.png)

**Comment by fernandadagostin** [comment]
I would like to try this.

**Comment by dfirebaugh** [comment]
That would be great!

also, numbers would be good if you're feeling ambitious

![alpha](https://user-images.githubusercontent.com/8050889/95703453-07d64580-0c1d-11eb-89b4-5d67f9e61f36.png)

**Comment by dfirebaugh** [comment]
@fernandadagostin  on second thought, All upper case may be better because you won't have to deal with things like the bottom of the letter y dropping below the bottom of the line

**Comment by fernandadagostin** [comment]
I was thinking to do Uppercase, Lowercase, and numbers. So you can have options. Also, I am putting the letters inside of 8x8 in the correct position to be shown, so I don't how that would work for you, but my thought is if you can get an 8x8 pice from this big image it should be good to show.
Note: I just finished uppercase, I will work on the lowercase and number now.

**Comment by dfirebaugh** [comment]
Ok, Sweet

thanks!

**Comment by dfirebaugh** [comment]
#55
