### ISSUE TITLE
shell: make the shell more like a standard shell

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#51]
Currently the screen clears after every command.

It would be nice to have a history of commands that we could use the up arrow or down arrow to recall those commands.

line wrapping would be nice.

Output is only one line.  It would be nice if we could format the output and have it respect newlines (i.e. `\n`)

Tab complete

Proper message when an invalid command is submitted.  Suggest that they type in help to see a list of commands.

What else is worth adding?  This doesn't need to be a full implementation of bash or sh

**Comment by tom-vthptvh** [comment]
Hi @dfirebaugh 
I would love to work on this issue ^^

**Comment by dfirebaugh** [comment]
Sweet!! go for it
