### ISSUE TITLE
sprite_editor: improve undo/redo

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#53]
The undo/redo works at the moment.  However, it's bound to `pen_tool`.
When we do a fill operation and then try to undo the fill operation, the undo will undo one pixel at a time.  

We should be able to undo/redo the entire fill operation.

Consider that we will eventually have a drag tool that will shift the entire sprite.

We also need to clear the undo/redo stack when we select a different sprite.

**Comment by jamessral** [comment]
Could I take a crack at this? I'd love to get better at C and graphics!
