### ISSUE TITLE
add a github action to test our standard build

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#73]
It would be cool if the readme included a icon for passing or failing the build

**Comment by yash2189** [comment]
@dfirebaugh can we use any build icon from this [Shields.io](https://shields.io/category/build) ?

**Comment by yash2189** [comment]
Can I take this up @dfirebaugh ?

**Comment by dfirebaugh** [comment]
Sure, do we need a token for this?

**Comment by yash2189** [comment]
Yes , while I was having a look on Shields.io they have asked a token while creating the badge.

> Sure, do we need a token for this?

**Comment by yash2189** [comment]
Hello @dfirebaugh I am getting the following error , it is showing repo,branch or workflow not found

<img width="700" alt="Capture_github" src="https://user-images.githubusercontent.com/31548778/96505671-14d5e300-1274-11eb-8f4f-53c225518ed8.PNG">

**Comment by yash2189** [comment]
@dfirebaugh Please review my PR #81
