### ISSUE TITLE
fix image output

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#8]
We should be able to output multiple file types.

### Convenient
It would be nice to output something like an encoded image that we can easily open on a computer.

### Small
Since we are limited to 16 colors, could we represent each pixel as a nibble?

Can we output the entire spritesheet in one file and each individual sprite in separate files?

We should also be able to load this file to make changes

**Comment by Costava** [comment]
[sfd](https://github.com/rxi/sfd) could be used to open a save dialog after `ctrl+s` is pressed.
[stb_image_write](https://github.com/nothings/stb/blob/master/stb_image_write.h) could be used to output the image file. PNG, BMP, TGA, JPEG, and HDR are supported. The type to use can be decided by the file extension entered in the save dialog.

Is outputting each individual sprite in separate files supposed to be automatic using some naming scheme? Or would the user choose a specific individual sprite to save?

If outputting each individual sprite is automatic, would all-black sprites be ignored?

If avoiding dependencies is a priority, [.ppm](https://en.wikipedia.org/wiki/Netpbm#File_formats) image files could be outputted easily without a library.
Also, SDL2 has [SDL_SaveBMP](https://wiki.libsdl.org/SDL_SaveBMP).

**Comment by dfirebaugh** [comment]
There isn't a strict priority on avoiding dependencies.  However, ppm seems pretty cool.

If you're working on this issue, I'd say do what you think is best.
We do need a way to ingest/import the file to edit it though.

I think all non-modified/black sprites could be ignored.


For the individual sprites, automated seems like it would be a better user experience.
