### ISSUE TITLE
Sprite Editor mouse events

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/spritely#84]
We need to be able to separate mouse events.  Some need to be momentary and some don't.

For now, they are momentary.
This allows for reasonable commits to the undo/redo stack.

Something like the drag tool should not be momentary because it keeps track of the mouse position to determine which direction to drag.  Also the pen tool is a little bit nicer when it's not momentary.  However, it will push a lot of commits to the undo/redo stack if it's not momentary

**Comment by gVirtu** [comment]
Hi @dfirebaugh !
I stumbled upon Spritely and really liked the project, even more so as I'd never tried Emscripten before. :)
So I decided to give this one a shot. I'm not sure if my approach was optimal so I'd love your feedback on this. I'll open a pull request for you to check when you have the time.
Thanks!
